/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Objetos.Aresta;
import Objetos.Objeto;
import Objetos.Ponto;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static revcg.RevCG.*;

/**
 *
 * @author Maycon
 */
public class Principal extends javax.swing.JFrame {

  /**
   * Variáveis globais
   */
  public ArrayList<Objeto> Obj; //objetos em cena
  public Graphics DT; //Topo
  public Graphics DF; //Frente
  public Graphics DL; //Lado
  public Graphics DP; //Pers
  public int mx = 170; //Meio em x
  public int my = 127; //Meio em y
  public Objeto objSelecionado;
  
  /**
   * Variaveis Locais Globais
   */
  byte cabecalho;
  JFileChooser fc = new JFileChooser();
  double EL, ET, EP, EF;
  
  /**
   * Creates new form Principal
   */
  public Principal() {
    try {
      UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel"); 
    } catch (Exception ex) { 
      ex.printStackTrace(); 
    }   
    initComponents();
    //Seta janela para o meio da tela, independente da resolucao.
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    this.setLocation(dim.width/2-this.getSize().width/2, 0);
    setResizable(false); //Nao deixa redimensionar a janela
    DT = pnlTopoI.getGraphics();
    //pnlTopoI.setBackground(Color.LIGHT_GRAY);
    DF = pnlFrenteI.getGraphics();
    //pnlFrenteI.setBackground(Color.LIGHT_GRAY);
    DL = pnlLadoI.getGraphics();
    //pnlLadoI.setBackground(Color.LIGHT_GRAY);
    DP = pnlPerspectivaI.getGraphics();
    //pnlPerspectivaI.setBackground(Color.LIGHT_GRAY);
    Obj = new ArrayList<>();
    LimpaPaineis();
    objSelecionado = new Objeto();
  }
  
  /**
   * Limpa tudo, tudo mesmo
   */
  public void LimpaTudo(){
    LimpaPaineis();
    Obj.clear();
  }
  
  /**
   * Limpa os paineis
   */
  public void LimpaPaineis(){
    DL.clearRect(0, 0, 340, 255);
    DF.clearRect(0, 0, 340, 255);
    DT.clearRect(0, 0, 340, 255);
    DP.clearRect(0, 0, 340, 255);
  }
  
  /**
   * Pinta todos paineis
   */
  public void PintaTudo(){
    LimpaPaineis();
    PintaLado();
    PintaTopo();
    PintaFrente();
    PintaPerspectiva();
  }
  
  /**
   * Simplificacao adotada:
   * escala(coordenada-centro)+centro
   * Baseada na distributiva de:
   * (Escala*coordenada)+((1-Escala)*Centro)
   */
  
  /**
   * Pinta o painel Lado
   */
  public void PintaLado(){
    for(Objeto o : Obj){
      for (Aresta a : o.arrAresta){
        DL.drawLine((int)(EL*((a.i.z)-o.C.z)+o.C.z)+mx, (int)(EL*((a.i.y)-o.C.y)+o.C.y), (int)(EL*((a.f.z)-o.C.z)+o.C.z)+mx, (int)(EL*((a.f.y)-o.C.y)+o.C.y));
      }
    }
  }
  
  /**
   * Pinta o painel Topo
   */
  public void PintaTopo(){
    for(Objeto o : Obj){
      for (Aresta a : o.arrAresta){
        DT.drawLine((int)(ET*((a.i.x)-o.C.x)+o.C.x)+mx, (int)(ET*((a.i.z)-o.C.z)+o.C.z)+my, (int)(ET*((a.f.x)-o.C.x)+o.C.x)+mx, (int)(ET*((a.f.z)-o.C.z)+o.C.z)+my);
      }
    }
  }
  
  /**
   * Pinta o painel Frente
   */
  public void PintaFrente(){
    for(Objeto o : Obj){
      for (Aresta a : o.arrAresta){
        DF.drawLine((int)(EF*((a.i.x)-o.C.x)+o.C.x)+mx, (int)(EF*((a.i.y)-o.C.y)+o.C.y), (int)(EF*((a.f.x)-o.C.x)+o.C.x)+mx, (int)(EF*((a.f.y)-o.C.y)+o.C.y));
      }
    }
  }
  
  /**
   * Pinta o painel de perspectiva
   */
  public void PintaPerspectiva(){
    
  }
  
  //////////////////////////////////////////////////////////////////////////////

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem2 = new javax.swing.JMenuItem();
    pnlTopo = new javax.swing.JPanel();
    pnlTopoI = new javax.swing.JPanel();
    btnAmpliarTopo = new javax.swing.JButton();
    ctrEscTopo = new javax.swing.JSpinner();
    jLabel5 = new javax.swing.JLabel();
    pnlMenus = new javax.swing.JTabbedPane();
    pnlObjetos = new javax.swing.JPanel();
    btnAdicionar = new javax.swing.JButton();
    pnlFerramentas = new javax.swing.JPanel();
    btnSelecionar = new javax.swing.JToggleButton();
    btnRedesenhar = new javax.swing.JButton();
    pnlAmbiente = new javax.swing.JPanel();
    ckbPropEscala = new javax.swing.JCheckBox();
    pnlFrente = new javax.swing.JPanel();
    pnlFrenteI = new javax.swing.JPanel();
    btnAmpliarFrente = new javax.swing.JButton();
    ctrEscFrente = new javax.swing.JSpinner();
    jLabel1 = new javax.swing.JLabel();
    pnlLado = new javax.swing.JPanel();
    pnlLadoI = new javax.swing.JPanel();
    btnAmpliarLado = new javax.swing.JButton();
    ctrEscLado = new javax.swing.JSpinner();
    jLabel4 = new javax.swing.JLabel();
    pnlPerspectiva = new javax.swing.JPanel();
    pnlPerspectivaI = new javax.swing.JPanel();
    btnAmpliarPerspectiva = new javax.swing.JButton();
    ctrEscPerspectiva = new javax.swing.JSpinner();
    jLabel3 = new javax.swing.JLabel();
    menuBar = new javax.swing.JMenuBar();
    menuArquivo = new javax.swing.JMenu();
    itemNovo = new javax.swing.JMenuItem();
    itemAbrir = new javax.swing.JMenuItem();
    itemSalvar = new javax.swing.JMenuItem();
    itemSalvarComo = new javax.swing.JMenuItem();
    menuEditar = new javax.swing.JMenu();
    menuAjuda = new javax.swing.JMenu();
    itemAjuda = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    itemSobre = new javax.swing.JMenuItem();

    jMenuItem2.setText("jMenuItem2");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("CGRev");

    pnlTopo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Topo"));
    pnlTopo.setPreferredSize(new java.awt.Dimension(350, 276));

    javax.swing.GroupLayout pnlTopoILayout = new javax.swing.GroupLayout(pnlTopoI);
    pnlTopoI.setLayout(pnlTopoILayout);
    pnlTopoILayout.setHorizontalGroup(
      pnlTopoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlTopoILayout.setVerticalGroup(
      pnlTopoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 255, Short.MAX_VALUE)
    );

    btnAmpliarTopo.setText("+");

    ctrEscTopo.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.001d, null, 0.1d));

    jLabel5.setText("Escala");

    javax.swing.GroupLayout pnlTopoLayout = new javax.swing.GroupLayout(pnlTopo);
    pnlTopo.setLayout(pnlTopoLayout);
    pnlTopoLayout.setHorizontalGroup(
      pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlTopoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopoLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ctrEscTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAmpliarTopo)
        .addContainerGap())
    );
    pnlTopoLayout.setVerticalGroup(
      pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopoLayout.createSequentialGroup()
        .addGroup(pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAmpliarTopo)
          .addComponent(ctrEscTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlTopoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pnlObjetos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
      public void mouseMoved(java.awt.event.MouseEvent evt) {
        pnlObjetosMouseMoved(evt);
      }
    });

    btnAdicionar.setText("Adicionar");
    btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAdicionarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlObjetosLayout = new javax.swing.GroupLayout(pnlObjetos);
    pnlObjetos.setLayout(pnlObjetosLayout);
    pnlObjetosLayout.setHorizontalGroup(
      pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlObjetosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        .addContainerGap())
    );
    pnlObjetosLayout.setVerticalGroup(
      pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlObjetosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnAdicionar)
        .addContainerGap(538, Short.MAX_VALUE))
    );

    pnlMenus.addTab("Objetos", pnlObjetos);

    btnSelecionar.setText("Selecionar");
    btnSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnSelecionarMouseClicked(evt);
      }
    });

    btnRedesenhar.setText("Redesenhar");
    btnRedesenhar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRedesenharActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlFerramentasLayout = new javax.swing.GroupLayout(pnlFerramentas);
    pnlFerramentas.setLayout(pnlFerramentasLayout);
    pnlFerramentasLayout.setHorizontalGroup(
      pnlFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlFerramentasLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnRedesenhar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        .addContainerGap())
    );
    pnlFerramentasLayout.setVerticalGroup(
      pnlFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlFerramentasLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnSelecionar)
        .addGap(18, 18, 18)
        .addComponent(btnRedesenhar)
        .addContainerGap(497, Short.MAX_VALUE))
    );

    pnlMenus.addTab("Ferramentas", null, pnlFerramentas, "");
    pnlFerramentas.getAccessibleContext().setAccessibleName("");
    pnlFerramentas.getAccessibleContext().setAccessibleDescription("");

    ckbPropEscala.setSelected(true);
    ckbPropEscala.setText("Proporcionalidade (Escala)");

    javax.swing.GroupLayout pnlAmbienteLayout = new javax.swing.GroupLayout(pnlAmbiente);
    pnlAmbiente.setLayout(pnlAmbienteLayout);
    pnlAmbienteLayout.setHorizontalGroup(
      pnlAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlAmbienteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(ckbPropEscala)
        .addContainerGap(17, Short.MAX_VALUE))
    );
    pnlAmbienteLayout.setVerticalGroup(
      pnlAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlAmbienteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(ckbPropEscala)
        .addContainerGap(542, Short.MAX_VALUE))
    );

    pnlMenus.addTab("Ambiente", pnlAmbiente);

    pnlFrente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Frente"));
    pnlFrente.setPreferredSize(new java.awt.Dimension(350, 276));

    pnlFrenteI.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlFrenteIMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout pnlFrenteILayout = new javax.swing.GroupLayout(pnlFrenteI);
    pnlFrenteI.setLayout(pnlFrenteILayout);
    pnlFrenteILayout.setHorizontalGroup(
      pnlFrenteILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlFrenteILayout.setVerticalGroup(
      pnlFrenteILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    btnAmpliarFrente.setText("+");

    ctrEscFrente.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.001d, null, 0.1d));

    jLabel1.setText("Escala");

    javax.swing.GroupLayout pnlFrenteLayout = new javax.swing.GroupLayout(pnlFrente);
    pnlFrente.setLayout(pnlFrenteLayout);
    pnlFrenteLayout.setHorizontalGroup(
      pnlFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlFrenteI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFrenteLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ctrEscFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAmpliarFrente)
        .addContainerGap())
    );
    pnlFrenteLayout.setVerticalGroup(
      pnlFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFrenteLayout.createSequentialGroup()
        .addGroup(pnlFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAmpliarFrente)
          .addComponent(ctrEscFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlFrenteI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlLado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lado"));
    pnlLado.setPreferredSize(new java.awt.Dimension(350, 276));

    pnlLadoI.setPreferredSize(new java.awt.Dimension(340, 255));
    pnlLadoI.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnlLadoIMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout pnlLadoILayout = new javax.swing.GroupLayout(pnlLadoI);
    pnlLadoI.setLayout(pnlLadoILayout);
    pnlLadoILayout.setHorizontalGroup(
      pnlLadoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlLadoILayout.setVerticalGroup(
      pnlLadoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 255, Short.MAX_VALUE)
    );

    btnAmpliarLado.setText("+");

    ctrEscLado.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.001d, null, 0.1d));
    ctrEscLado.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        ctrEscLadoStateChanged(evt);
      }
    });

    jLabel4.setText("Escala");

    javax.swing.GroupLayout pnlLadoLayout = new javax.swing.GroupLayout(pnlLado);
    pnlLado.setLayout(pnlLadoLayout);
    pnlLadoLayout.setHorizontalGroup(
      pnlLadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlLadoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLadoLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ctrEscLado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAmpliarLado)
        .addContainerGap())
    );
    pnlLadoLayout.setVerticalGroup(
      pnlLadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLadoLayout.createSequentialGroup()
        .addGroup(pnlLadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAmpliarLado)
          .addComponent(ctrEscLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(pnlLadoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pnlPerspectiva.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perspectiva"));
    pnlPerspectiva.setPreferredSize(new java.awt.Dimension(350, 276));

    javax.swing.GroupLayout pnlPerspectivaILayout = new javax.swing.GroupLayout(pnlPerspectivaI);
    pnlPerspectivaI.setLayout(pnlPerspectivaILayout);
    pnlPerspectivaILayout.setHorizontalGroup(
      pnlPerspectivaILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlPerspectivaILayout.setVerticalGroup(
      pnlPerspectivaILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    btnAmpliarPerspectiva.setText("+");

    ctrEscPerspectiva.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.001d, null, 0.1d));

    jLabel3.setText("Escala");

    javax.swing.GroupLayout pnlPerspectivaLayout = new javax.swing.GroupLayout(pnlPerspectiva);
    pnlPerspectiva.setLayout(pnlPerspectivaLayout);
    pnlPerspectivaLayout.setHorizontalGroup(
      pnlPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPerspectivaI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerspectivaLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(ctrEscPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAmpliarPerspectiva)
        .addContainerGap())
    );
    pnlPerspectivaLayout.setVerticalGroup(
      pnlPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPerspectivaLayout.createSequentialGroup()
        .addGroup(pnlPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAmpliarPerspectiva)
          .addComponent(ctrEscPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pnlPerspectivaI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menuArquivo.setText("Arquivo");

    itemNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
    itemNovo.setText("Novo");
    itemNovo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemNovoActionPerformed(evt);
      }
    });
    menuArquivo.add(itemNovo);

    itemAbrir.setText("Abrir");
    itemAbrir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemAbrirActionPerformed(evt);
      }
    });
    menuArquivo.add(itemAbrir);

    itemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    itemSalvar.setText("Salvar");
    itemSalvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemSalvarActionPerformed(evt);
      }
    });
    menuArquivo.add(itemSalvar);

    itemSalvarComo.setText("Salvar Como");
    menuArquivo.add(itemSalvarComo);

    menuBar.add(menuArquivo);

    menuEditar.setText("Editar");
    menuBar.add(menuEditar);

    menuAjuda.setText("Ajuda");

    itemAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    itemAjuda.setText("Tópicos de ajuda");
    menuAjuda.add(itemAjuda);
    menuAjuda.add(jSeparator1);

    itemSobre.setText("Sobre");
    itemSobre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemSobreActionPerformed(evt);
      }
    });
    menuAjuda.add(itemSobre);

    menuBar.add(menuAjuda);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pnlLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pnlPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pnlFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(pnlMenus)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(pnlLado, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
              .addComponent(pnlFrente, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pnlTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
              .addComponent(pnlPerspectiva, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
          .addComponent(pnlMenus))
        .addContainerGap())
    );

    pnlMenus.getAccessibleContext().setAccessibleName("pnlTabs");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
    this.setEnabled(false);
    new Sobre(this).setVisible(true);
  }//GEN-LAST:event_itemSobreActionPerformed

  private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
    this.setEnabled(false);
    new Perfil(this).setVisible(true);
  }//GEN-LAST:event_btnAdicionarActionPerformed

  private void pnlObjetosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlObjetosMouseMoved
    PintaTudo();
  }//GEN-LAST:event_pnlObjetosMouseMoved

  private void itemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovoActionPerformed
    if(!Obj.isEmpty()){
      //TODO Confirmacao
      LimpaTudo();
    } else {
      LimpaTudo();
    }
  }//GEN-LAST:event_itemNovoActionPerformed

  private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
    fc = new JFileChooser();
    byte r;
    double xi, yi, zi, xf, yf, zf;
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      String s = file.toString();
      if (!file.canRead()) {
        JOptionPane.showMessageDialog(this, "Nao foi possivel ler o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
      }
      try {
        DataInputStream entr = new DataInputStream(new FileInputStream(s));
        cabecalho = entr.readByte();
        LimpaTudo();
        while (entr.available() > 0) { //Le
          r = entr.readByte();
          if (r == 0){ //Objeto
            Obj.add(new Objeto());
          } else if (r == 1){ //Ponto
            Obj.get(Obj.size()-1).arrPonto.add(new Ponto(entr.readDouble(), entr.readDouble(), entr.readDouble()));
          } else if (r == 2){ //Aresta
            Obj.get(Obj.size()-1).arrAresta.add(new Aresta(new Ponto(entr.readDouble(), entr.readDouble(), entr.readDouble()), new Ponto(entr.readDouble(), entr.readDouble(), entr.readDouble())));
          } else {
            JOptionPane.showMessageDialog(this, "Identificador invalido", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
          }
        }
      } catch (FileNotFoundException ex) {
        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Nao foi possivel ler o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
      } catch (IOException ex) {
        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erro generico de leitura", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
      }
    }
    LimpaPaineis();
    PintaTudo();
    LimpaPaineis();
    PintaTudo();
  }//GEN-LAST:event_itemAbrirActionPerformed

  private void btnSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelecionarMouseClicked
    if(btnSelecionar.isSelected()){
      //System.out.println("Prendi");
    } else {
      //System.out.println("Soltei");
    }
  }//GEN-LAST:event_btnSelecionarMouseClicked

  private void pnlLadoIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLadoIMouseClicked
    if(btnSelecionar.isSelected()){
      //System.out.println("Policia");
      Ponto p = new Ponto();
      p.x = evt.getX(); //*0.25 0~340
      p.y = evt.getY(); //*0.25 0~255
      
    } else {
      //System.out.println("Juiz");
    }
  }//GEN-LAST:event_pnlLadoIMouseClicked

  private void pnlFrenteIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFrenteIMouseClicked
    if(btnSelecionar.isSelected()){
      //System.out.println("Policia");
    } else {
      //System.out.println("Juiz");
    }
  }//GEN-LAST:event_pnlFrenteIMouseClicked

  private void itemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalvarActionPerformed
    fc = new JFileChooser();
    int returnVal = fc.showSaveDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File file = fc.getSelectedFile();
      String s = file.toString() + ".acr"; //Arquivo CGRev (Perfil, cena)
      //System.out.println("Saida = " + s);
      cabecalho = (byte) (VERSAO_CENA << 4);
      try {
        try (DataOutputStream said = new DataOutputStream(new FileOutputStream(s))) {
          said.writeByte(cabecalho);
          for (Objeto o : Obj) {
            said.writeByte(0);
            for (Ponto p : o.arrPonto) {
              said.writeByte(1);
              said.writeDouble(p.x);
              said.writeDouble(p.y);
              said.writeDouble(p.z);
            }
            for (Aresta a : o.arrAresta) {
              said.writeByte(2);
              said.writeDouble(a.i.x);
              said.writeDouble(a.i.y);
              said.writeDouble(a.i.z);
              said.writeDouble(a.f.x);
              said.writeDouble(a.f.y);
              said.writeDouble(a.f.z);
            }
          }
        }
      } catch (FileNotFoundException ex) {
        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
        Logger.getLogger(Perfil.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }//GEN-LAST:event_itemSalvarActionPerformed

  private void btnRedesenharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedesenharActionPerformed
    LimpaPaineis();
    PintaTudo();
  }//GEN-LAST:event_btnRedesenharActionPerformed

  private void ctrEscLadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ctrEscLadoStateChanged
    //z, y
    String input = ctrEscLado.getValue().toString();
    EL = 1;
    if (input.isEmpty()) {
      ctrEscLado.setValue(1);
    } else {
      try {
        EL = Double.parseDouble(input);
      } catch (NumberFormatException | NullPointerException e) {
        ctrEscLado.setValue(1);
      }
    }
    if(ckbPropEscala.isSelected()){
      ET = EL;
      EP = EL;
      EF = EL;
      ctrEscPerspectiva.setValue(EL);
      ctrEscTopo.setValue(EL);
      ctrEscFrente.setValue(EL);
    }
    PintaTudo();
  }//GEN-LAST:event_ctrEscLadoStateChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Windows look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }*/
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Principal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdicionar;
  private javax.swing.JButton btnAmpliarFrente;
  private javax.swing.JButton btnAmpliarLado;
  private javax.swing.JButton btnAmpliarPerspectiva;
  private javax.swing.JButton btnAmpliarTopo;
  private javax.swing.JButton btnRedesenhar;
  private javax.swing.JToggleButton btnSelecionar;
  private javax.swing.JCheckBox ckbPropEscala;
  private javax.swing.JSpinner ctrEscFrente;
  private javax.swing.JSpinner ctrEscLado;
  private javax.swing.JSpinner ctrEscPerspectiva;
  private javax.swing.JSpinner ctrEscTopo;
  private javax.swing.JMenuItem itemAbrir;
  private javax.swing.JMenuItem itemAjuda;
  private javax.swing.JMenuItem itemNovo;
  private javax.swing.JMenuItem itemSalvar;
  private javax.swing.JMenuItem itemSalvarComo;
  private javax.swing.JMenuItem itemSobre;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JMenu menuAjuda;
  private javax.swing.JMenu menuArquivo;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuEditar;
  private javax.swing.JPanel pnlAmbiente;
  private javax.swing.JPanel pnlFerramentas;
  private javax.swing.JPanel pnlFrente;
  private javax.swing.JPanel pnlFrenteI;
  private javax.swing.JPanel pnlLado;
  private javax.swing.JPanel pnlLadoI;
  private javax.swing.JTabbedPane pnlMenus;
  private javax.swing.JPanel pnlObjetos;
  private javax.swing.JPanel pnlPerspectiva;
  private javax.swing.JPanel pnlPerspectivaI;
  private javax.swing.JPanel pnlTopo;
  private javax.swing.JPanel pnlTopoI;
  // End of variables declaration//GEN-END:variables
}
