/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Objetos.Aresta;
import Objetos.Objeto;
import Objetos.Ponto;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.UIManager;

/**
 *
 * @author Maycon
 */
public class Principal extends javax.swing.JFrame {

  /**
   * Variáveis globais
   */
  public ArrayList<Objeto> Obj; //objetos em cena
  public Graphics DT; //Topo
  public Graphics DF; //Frente
  public Graphics DL; //Lado
  public Graphics DP; //Pers
  public int mx = 170; //Meio em x
  public int my = 127; //Meio em y
  
  /**
   * Creates new form Principal
   */
  public Principal() {
    try {
      UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel"); 
    } catch (Exception ex) { 
      ex.printStackTrace(); 
    }   
    initComponents();
    //Seta janela para o meio da tela, independente da resolução.
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    //this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    setResizable(false); //Nao deixa redimensionar a janela
    DT = pnlTopoI.getGraphics();
    DF = pnlFrenteI.getGraphics();
    DL = pnlLadoI.getGraphics();
    DP = pnlPerspectivaI.getGraphics();
    Obj = new ArrayList<>();
  }
  
  public void PintaTudo(){
    PintaLado();
    PintaTopo();
    PintaFrente();
    PintaPerspectiva();
  }
  
  /**
   * Pinta o painel Lado
   */
  public void PintaLado(){
    
  }
  
  /**
   * Pinta o painel Topo
   */
  public void PintaTopo(){
    for(Objeto o : Obj){
      for (Aresta a : o.arrAresta){
        DT.drawLine((int)a.i.x+mx, (int)a.i.z+my, (int)a.f.x+mx, (int)a.f.z+my);
      }
    }
  }
  
  /**
   * Pinta o painel Frente
   */
  public void PintaFrente(){
    
  }
  
  /**
   * Pinta o painel de perspectiva
   */
  public void PintaPerspectiva(){
    
  }
  
  //////////////////////////////////////////////////////////////////////////////

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuItem2 = new javax.swing.JMenuItem();
    pnlTopo = new javax.swing.JPanel();
    pnlTopoI = new javax.swing.JPanel();
    pnlMenus = new javax.swing.JTabbedPane();
    pnlObjetos = new javax.swing.JPanel();
    btnAdicionar = new javax.swing.JButton();
    pnlFerramentas = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    pnlAmbiente = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    pnlFrente = new javax.swing.JPanel();
    pnlFrenteI = new javax.swing.JPanel();
    pnlLado = new javax.swing.JPanel();
    pnlLadoI = new javax.swing.JPanel();
    pnlPerspectiva = new javax.swing.JPanel();
    pnlPerspectivaI = new javax.swing.JPanel();
    menuBar = new javax.swing.JMenuBar();
    menuArquivo = new javax.swing.JMenu();
    itemNovo = new javax.swing.JMenuItem();
    itemAbrir = new javax.swing.JMenuItem();
    itemSalvar = new javax.swing.JMenuItem();
    itemSalvarComo = new javax.swing.JMenuItem();
    menuAjuda = new javax.swing.JMenu();
    itemAjuda = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    itemSobre = new javax.swing.JMenuItem();

    jMenuItem2.setText("jMenuItem2");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    pnlTopo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Topo"));
    pnlTopo.setPreferredSize(new java.awt.Dimension(350, 276));

    javax.swing.GroupLayout pnlTopoILayout = new javax.swing.GroupLayout(pnlTopoI);
    pnlTopoI.setLayout(pnlTopoILayout);
    pnlTopoILayout.setHorizontalGroup(
      pnlTopoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlTopoILayout.setVerticalGroup(
      pnlTopoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 255, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout pnlTopoLayout = new javax.swing.GroupLayout(pnlTopo);
    pnlTopo.setLayout(pnlTopoLayout);
    pnlTopoLayout.setHorizontalGroup(
      pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlTopoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlTopoLayout.setVerticalGroup(
      pnlTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlTopoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    btnAdicionar.setText("Adicionar");
    btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAdicionarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlObjetosLayout = new javax.swing.GroupLayout(pnlObjetos);
    pnlObjetos.setLayout(pnlObjetosLayout);
    pnlObjetosLayout.setHorizontalGroup(
      pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlObjetosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        .addContainerGap())
    );
    pnlObjetosLayout.setVerticalGroup(
      pnlObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlObjetosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnAdicionar)
        .addContainerGap(481, Short.MAX_VALUE))
    );

    pnlMenus.addTab("Objetos", pnlObjetos);

    jLabel1.setText("jLabel1");

    javax.swing.GroupLayout pnlFerramentasLayout = new javax.swing.GroupLayout(pnlFerramentas);
    pnlFerramentas.setLayout(pnlFerramentasLayout);
    pnlFerramentasLayout.setHorizontalGroup(
      pnlFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlFerramentasLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(130, Short.MAX_VALUE))
    );
    pnlFerramentasLayout.setVerticalGroup(
      pnlFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlFerramentasLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addContainerGap(490, Short.MAX_VALUE))
    );

    pnlMenus.addTab("Ferramentas", null, pnlFerramentas, "");
    pnlFerramentas.getAccessibleContext().setAccessibleName("");
    pnlFerramentas.getAccessibleContext().setAccessibleDescription("");

    jLabel2.setText("jLabel2");

    javax.swing.GroupLayout pnlAmbienteLayout = new javax.swing.GroupLayout(pnlAmbiente);
    pnlAmbiente.setLayout(pnlAmbienteLayout);
    pnlAmbienteLayout.setHorizontalGroup(
      pnlAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlAmbienteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addContainerGap(130, Short.MAX_VALUE))
    );
    pnlAmbienteLayout.setVerticalGroup(
      pnlAmbienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlAmbienteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addContainerGap(490, Short.MAX_VALUE))
    );

    pnlMenus.addTab("Ambiente", pnlAmbiente);

    pnlFrente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Frente"));
    pnlFrente.setPreferredSize(new java.awt.Dimension(350, 276));

    javax.swing.GroupLayout pnlFrenteILayout = new javax.swing.GroupLayout(pnlFrenteI);
    pnlFrenteI.setLayout(pnlFrenteILayout);
    pnlFrenteILayout.setHorizontalGroup(
      pnlFrenteILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlFrenteILayout.setVerticalGroup(
      pnlFrenteILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 255, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout pnlFrenteLayout = new javax.swing.GroupLayout(pnlFrente);
    pnlFrente.setLayout(pnlFrenteLayout);
    pnlFrenteLayout.setHorizontalGroup(
      pnlFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlFrenteI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlFrenteLayout.setVerticalGroup(
      pnlFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlFrenteI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pnlLado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lado"));
    pnlLado.setPreferredSize(new java.awt.Dimension(350, 276));

    pnlLadoI.setPreferredSize(new java.awt.Dimension(340, 255));

    javax.swing.GroupLayout pnlLadoILayout = new javax.swing.GroupLayout(pnlLadoI);
    pnlLadoI.setLayout(pnlLadoILayout);
    pnlLadoILayout.setHorizontalGroup(
      pnlLadoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlLadoILayout.setVerticalGroup(
      pnlLadoILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 255, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout pnlLadoLayout = new javax.swing.GroupLayout(pnlLado);
    pnlLado.setLayout(pnlLadoLayout);
    pnlLadoLayout.setHorizontalGroup(
      pnlLadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlLadoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlLadoLayout.setVerticalGroup(
      pnlLadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlLadoI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pnlPerspectiva.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perspectiva"));
    pnlPerspectiva.setPreferredSize(new java.awt.Dimension(350, 276));

    javax.swing.GroupLayout pnlPerspectivaILayout = new javax.swing.GroupLayout(pnlPerspectivaI);
    pnlPerspectivaI.setLayout(pnlPerspectivaILayout);
    pnlPerspectivaILayout.setHorizontalGroup(
      pnlPerspectivaILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 340, Short.MAX_VALUE)
    );
    pnlPerspectivaILayout.setVerticalGroup(
      pnlPerspectivaILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 255, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout pnlPerspectivaLayout = new javax.swing.GroupLayout(pnlPerspectiva);
    pnlPerspectiva.setLayout(pnlPerspectivaLayout);
    pnlPerspectivaLayout.setHorizontalGroup(
      pnlPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPerspectivaI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pnlPerspectivaLayout.setVerticalGroup(
      pnlPerspectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(pnlPerspectivaI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    menuArquivo.setText("Arquivo");

    itemNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
    itemNovo.setText("Novo");
    menuArquivo.add(itemNovo);

    itemAbrir.setText("Abrir");
    menuArquivo.add(itemAbrir);

    itemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    itemSalvar.setText("Salvar");
    menuArquivo.add(itemSalvar);

    itemSalvarComo.setText("Salvar Como");
    menuArquivo.add(itemSalvarComo);

    menuBar.add(menuArquivo);

    menuAjuda.setText("Ajuda");

    itemAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    itemAjuda.setText("Tópicos de ajuda");
    menuAjuda.add(itemAjuda);
    menuAjuda.add(jSeparator1);

    itemSobre.setText("Sobre");
    itemSobre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        itemSobreActionPerformed(evt);
      }
    });
    menuAjuda.add(itemSobre);

    menuBar.add(menuAjuda);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pnlLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pnlPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(pnlFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(pnlMenus)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pnlFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(pnlLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pnlTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(pnlPerspectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(pnlMenus))
        .addContainerGap())
    );

    pnlMenus.getAccessibleContext().setAccessibleName("pnlTabs");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
    this.setEnabled(false);
    new Sobre(this).setVisible(true);
  }//GEN-LAST:event_itemSobreActionPerformed

  private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
    this.setEnabled(false);
    new Perfil(this).setVisible(true);
  }//GEN-LAST:event_btnAdicionarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Windows look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }*/
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Principal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdicionar;
  private javax.swing.JMenuItem itemAbrir;
  private javax.swing.JMenuItem itemAjuda;
  private javax.swing.JMenuItem itemNovo;
  private javax.swing.JMenuItem itemSalvar;
  private javax.swing.JMenuItem itemSalvarComo;
  private javax.swing.JMenuItem itemSobre;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JMenu menuAjuda;
  private javax.swing.JMenu menuArquivo;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JPanel pnlAmbiente;
  private javax.swing.JPanel pnlFerramentas;
  private javax.swing.JPanel pnlFrente;
  private javax.swing.JPanel pnlFrenteI;
  private javax.swing.JPanel pnlLado;
  private javax.swing.JPanel pnlLadoI;
  private javax.swing.JTabbedPane pnlMenus;
  private javax.swing.JPanel pnlObjetos;
  private javax.swing.JPanel pnlPerspectiva;
  private javax.swing.JPanel pnlPerspectivaI;
  private javax.swing.JPanel pnlTopo;
  private javax.swing.JPanel pnlTopoI;
  // End of variables declaration//GEN-END:variables
}
